name: "CD"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        default: latest
        required: true
      skiptest:
        description: 'Skip Test'
        type: boolean
        required: false
      skipbuild:
        description: 'Skip Build'
        type: boolean
        required: false
#  schedule:
#    - cron: '0 5 * * *'

jobs:
  test:
    if: ${{ github.event.inputs.skiptest }} == true
    runs-on: ubuntu-latest
    steps:
      - name: Test Go
        run: go test -v ./...
  build:
    if: ${{ github.event.inputs.skipbuild }} == true
    runs-on: ubuntu-latest
    steps:
      - name: Build Go
        run: go build -v ./...
  publish:
    runs-on: ubuntu-latest
    needs:
      - test
      - build
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch Go Modules
        run: go mod download
      
      - name: Docker Build
        run: docker build -t go-sample .

      - name: "Login to DockerHub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: "Build and Push"
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: fahaberdiev/go-sample:${{ github.event.inputs.tag }}
